### ISSUE TITLE
Django 1.10 doesn't work out of the box

### ISSUE THREAD

**Issue by markfinger** [ixc/ixc-project-template#32]
Looks like polymorphic's out of date

```
(choice-everything-database)~/Projects/choice-everything-database $ ./manage.py runserver
# Importing BASE_SETTINGS_MODULE: develop
# Importing BASE_SETTINGS_MODULE: develop
Unhandled exception in thread started by <function wrapper at 0x1050918c0>
Traceback (most recent call last):
  File "/Users/markfinger/Projects/virtualenvs/choice-everything-database/lib/python2.7/site-packages/django/utils/autoreload.py", line 226, in wrapper
    fn(*args, **kwargs)
  File "/Users/markfinger/Projects/virtualenvs/choice-everything-database/lib/python2.7/site-packages/django/core/management/commands/runserver.py", line 113, in inner_run
    autoreload.raise_last_exception()
  File "/Users/markfinger/Projects/virtualenvs/choice-everything-database/lib/python2.7/site-packages/django/utils/autoreload.py", line 249, in raise_last_exception
    six.reraise(*_exception)
  File "/Users/markfinger/Projects/virtualenvs/choice-everything-database/lib/python2.7/site-packages/django/utils/autoreload.py", line 226, in wrapper
    fn(*args, **kwargs)
  File "/Users/markfinger/Projects/virtualenvs/choice-everything-database/lib/python2.7/site-packages/django/__init__.py", line 27, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/Users/markfinger/Projects/virtualenvs/choice-everything-database/lib/python2.7/site-packages/django/apps/registry.py", line 85, in populate
    app_config = AppConfig.create(entry)
  File "/Users/markfinger/Projects/virtualenvs/choice-everything-database/lib/python2.7/site-packages/django/apps/config.py", line 90, in create
    module = import_module(entry)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/Users/markfinger/Projects/virtualenvs/choice-everything-database/lib/python2.7/site-packages/polymorphic/__init__.py", line 11, in <module>
    from .polymorphic_model import PolymorphicModel
  File "/Users/markfinger/Projects/virtualenvs/choice-everything-database/lib/python2.7/site-packages/polymorphic/polymorphic_model.py", line 19, in <module>
    from django.contrib.contenttypes.models import ContentType
  File "/Users/markfinger/Projects/virtualenvs/choice-everything-database/lib/python2.7/site-packages/django/contrib/contenttypes/models.py", line 138, in <module>
    class ContentType(models.Model):
  File "/Users/markfinger/Projects/virtualenvs/choice-everything-database/lib/python2.7/site-packages/django/db/models/base.py", line 105, in __new__
    app_config = apps.get_containing_app_config(module)
  File "/Users/markfinger/Projects/virtualenvs/choice-everything-database/lib/python2.7/site-packages/django/apps/registry.py", line 237, in get_containing_app_config
    self.check_apps_ready()
  File "/Users/markfinger/Projects/virtualenvs/choice-everything-database/lib/python2.7/site-packages/django/apps/registry.py", line 124, in check_apps_ready
    raise AppRegistryNotReady("Apps aren't loaded yet.")
django.core.exceptions.AppRegistryNotReady: Apps aren't loaded yet.
```

**Comment by markfinger** [comment]
Note that I ran the above with most of icekit and fluent turned off, it's likely that there are other problems deep in those libraries.

@mrmachine I noticed that the django version is pinned to the latest LTS, `'Django>=1.8,<1.9',  # LTS` in 'setup.py`. Is the intention to sit on that version until the next one?
